name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v1.0.0  # Replace with your desired tag name
