name: Build RedisEntityBridge 1.0.0

on:
  push:
    branches: [ "ver/1.0.0" ]
  pull_request:
    branches: [ "ver/1.0.0" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  post:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: RedisEntityBridge-1.0.0
          path: target/*SNAPSHOT.jar
