name: Build RedisEntityBridge 1.0.0

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: RedisEntityBridge-1.0.0
          path: target/*SNAPSHOT.jar
      - name: Release RedisEntityBridge
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "RedisEntityBridge-1.0.0"
          automatic_release_tag: "release-1.0.0"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "target/*SNAPSHOT.jar"
          prerelease: false
      
